# Generated by Django 5.1.3 on 2025-05-13 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_chambre'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChambreDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_cables_entree', models.IntegerField()),
                ('nb_cables_sortie', models.IntegerField()),
                ('type_boitier', models.CharField(max_length=100)),
                ('commentaire', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='chambre_photos/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='myapp.chambre')),
            ],
        ),
    ]
