# Generated by Django 5.1.3 on 2025-05-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_chambredetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeteDeCable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('type_odf', models.CharField(max_length=100)),
                ('nb_ports', models.IntegerField()),
                ('ports_utilises', models.CharField(max_length=100)),
                ('depart', models.CharField(max_length=100)),
                ('arrivee', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='tetes_cable_photos/')),
                ('description', models.TextField(blank=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
