# Generated by Django 5.1.3 on 2025-05-21 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_tetedecable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChambreTirageDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_conduits', models.IntegerField()),
                ('commentaire', models.TextField(blank=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tirage_details', to='myapp.chambre')),
            ],
        ),
    ]
