# Generated by Django 5.1.3 on 2025-05-21 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_chambretiragedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='chambretiragedetail',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='chambre_tirage_photos/'),
        ),
    ]
